# Generated by Django 5.0 on 2025-11-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='assignment_status',
            field=models.CharField(choices=[('none', 'No driver'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
